### ISSUE TITLE
Language Selection Empty 

### ISSUE THREAD

**Issue by gnogeek** [Diagg/MDT-Cloud#1]
Hello,

First thanks for your incredible script.

I having the following issue when i try to deploy, it don't find any language for Windows 10 May 2021 its just empty.

Any to fix it?
![image](https://user-images.githubusercontent.com/77178414/134069547-21c588cf-a488-4b32-9649-08052843d6b8.png)

**Comment by Diagg** [comment]
Hi, i've seen this one poping on few occasion, I've reworked the way releases are gathered from the internet to avoid this. Please give me a few days to release a new package that will fix it.

**Comment by Diagg** [comment]
Hi, the issue should be fixed in version 2.0 published two months ago... sorry for closing the topic
